
#ccgcc and ccld are cross-compile-gcc and cross-compile-ld resepctively
#they were necessary because mac gcc(clang) does not support -Ttext or --oformat
#if you are on windows or linux you should be able to simply use your regular gcc toolkit
alias ccgcc="/usr/local/gcc-4.8.1-for-linux32/bin/i586-pc-linux-gcc"
alias ccld="/usr/local/gcc-4.8.1-for-linux32/bin/i586-pc-linux-ld"

nasm boots.asm -o boots.bin
ccgcc clib/main.c -c -ffreestanding -o clib/main.o
ccld clib/main.o -Ttext 0x1000 -o clib/main.bin --oformat binary
cat boots.bin clib/main.bin > os-image
dd if=os-image of=/dev/disk2 conv=notrunc bs=512
